#!/usr/local/bin/perl
use lib qw(lib ../lib);
use strict;
use Bio::DasLite;
use Data::Dumper;
$Bio::DasLite::DEBUG = 1;
my $dl    = Bio::DasLite->new();
my $style = qq(<STYLESHEET version="1.0">
    <CATEGORY id="decipher">
      <TYPE id="0">
        <GLYPH>
          <BOX>
            <HEIGHT>0</HEIGHT>
            <FGCOLOR>zero</FGCOLOR>
          </BOX>
        </GLYPH>
      </TYPE>
      <TYPE id="1>
        <GLYPH>
          <LINE>
            <HEIGHT>1</HEIGHT>
            <FGCOLOR>one</FGCOLOR>
          </LINE>
        </GLYPH>
      </TYPE>
    </CATEGORY>
  </STYLESHEET>);


my $results = [];
my $attr    = $Bio::DasLite::ATTR->{'stylesheet'};
$dl->_parse_branch("file", $results, $attr, $style, 1);

#print Dumper $attr;
print Dumper $results;
