#!/usr/local/bin/perl -wT
use lib qw(../blib ../lib);
use strict;
use Bio::DasLite;
use Data::Dumper;
$| = 1;

my @sources = ();
push @sources, "http://servlet.sanger.ac.uk/das/ensembl1834";
push @sources, "http://das.sanger.ac.uk/das/cosmic_genomic";
push @sources, "http://das.sanger.ac.uk/das/decipher";
push @sources, "http://das.sanger.ac.uk/das/swissprot";

my $das = Bio::DasLite->new({
			       'timeout'    => 30,
			       'http_proxy' => "http://webcache.sanger.ac.uk:3128/",
			       'dsn'        => \@sources,
			      });
print "\n", "*"x80, "\n", Dumper $das->dsns();

print "\n", "*"x80, "\n", Dumper $das->features([
						 {'segment' => "1:1,1000000",'type' => 'karyotype',},
						 {'segment' => "2:1,1000000",},
						 {'segment' => "1:1,1000",},
						]);

print "\n", "*"x80, "\n", Dumper $das->types();
print "\n", "*"x80, "\n", Dumper $das->sequence("2:1,1000");
print "\n", "*"x80, "\n", Dumper $das->entry_points();

print "\n", "*"x80, "\n", Dumper $das->features("DYNA_CHICK");
